//! CRKB bigram language model: compact word-pair scores for context
//! re-ranking.
//!
//! Data is generated by `utils/gen_bigram_blob.py` from Peter Norvig's
//! published Google Web Trillion Word Corpus bigram counts, filtered to our
//! dictionary vocabulary. Word IDs index into the CRKD dictionary blob's
//! entry order (the corpus order [`crate::NlpEngine::corpus_words`] holds),
//! so the model ships no vocabulary table of its own.
//!
//! Same trust posture as the dictionary blob: every declared length is
//! checked before use, and the (id1, id2) sort order the binary-search
//! lookup depends on is VERIFIED during parse, not assumed — a corrupt or
//! resorted blob is rejected as a whole rather than answering wrongly.
//!
//! Format (little-endian):
//! ```text
//! magic       b"CRKB"
//! version     u8 = 2
//! count       u32
//! vocab_count u32   // dictionary size this table was generated against
//! entry*      { id1: u32, id2: u32, score: u8 }   // 9 bytes each
//! ```
//! Scores are quantized log2(pair count) * 8 — comparable only with each
//! other, which is all re-ranking needs.
//!
//! `vocab_count` exists because ids are POSITIONAL into the dictionary
//! blob's order: a bigram table generated against a different dictionary
//! would silently score the wrong words. The loader compares it against the
//! live corpus size and rejects mismatches outright.

pub const BIGRAM_MAGIC: [u8; 4] = *b"CRKB";
pub const BIGRAM_VERSION: u8 = 2;
/// Far above the shipped table (~245k), low enough that a corrupt count
/// cannot drive unbounded allocation.
pub const MAX_PAIRS: u32 = 4_000_000;

const HEADER_LEN: usize = 4 + 1 + 4 + 4;
const ENTRY_LEN: usize = 9;

#[derive(Debug, PartialEq, Eq)]
pub enum BigramError {
    NotOurs,
    CountTooLarge(u32),
    Truncated,
    NotSorted,
    /// The table was generated against a different dictionary.
    VocabMismatch { expected: u32, found: u32 },
}

/// A parsed, lookup-ready bigram table.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct BigramModel {
    entries: Vec<(u32, u32, u8)>,
}

impl BigramModel {
    /// `expected_vocab` is the size of the dictionary corpus currently
    /// loaded; a table generated against any other dictionary is rejected.
    pub fn parse(data: &[u8], expected_vocab: u32) -> Result<Self, BigramError> {
        if data.len() < HEADER_LEN || data[0..4] != BIGRAM_MAGIC || data[4] != BIGRAM_VERSION {
            return Err(BigramError::NotOurs);
        }
        let count = u32::from_le_bytes([data[5], data[6], data[7], data[8]]);
        if count > MAX_PAIRS {
            return Err(BigramError::CountTooLarge(count));
        }
        let vocab = u32::from_le_bytes([data[9], data[10], data[11], data[12]]);
        if vocab != expected_vocab {
            return Err(BigramError::VocabMismatch {
                expected: expected_vocab,
                found: vocab,
            });
        }
        let needed = HEADER_LEN + count as usize * ENTRY_LEN;
        if data.len() < needed {
            return Err(BigramError::Truncated);
        }
        let mut entries = Vec::with_capacity(count as usize);
        let mut prev_key: Option<(u32, u32)> = None;
        for chunk in data[HEADER_LEN..needed].chunks_exact(ENTRY_LEN) {
            let id1 = u32::from_le_bytes([chunk[0], chunk[1], chunk[2], chunk[3]]);
            let id2 = u32::from_le_bytes([chunk[4], chunk[5], chunk[6], chunk[7]]);
            let key = (id1, id2);
            if let Some(prev) = prev_key {
                if key <= prev {
                    return Err(BigramError::NotSorted);
                }
            }
            prev_key = Some(key);
            entries.push((id1, id2, chunk[8]));
        }
        Ok(Self { entries })
    }

    pub fn len(&self) -> usize {
        self.entries.len()
    }

    pub fn is_empty(&self) -> bool {
        self.entries.is_empty()
    }

    /// Quantized log-count score for the pair, `None` when unseen.
    /// All (prev, next, score) entries whose prev is `id1`, in id order —
    /// the entries vec is sorted, so this is a binary-searched range.
    pub fn successors(&self, id1: u32) -> &[(u32, u32, u8)] {
        let start = self.entries.partition_point(|e| e.0 < id1);
        let end = self.entries.partition_point(|e| e.0 <= id1);
        &self.entries[start..end]
    }

    pub fn score(&self, id1: u32, id2: u32) -> Option<u8> {
        self.entries
            .binary_search_by_key(&(id1, id2), |&(a, b, _)| (a, b))
            .ok()
            .map(|i| self.entries[i].2)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const VOCAB: u32 = 100;

    fn encode(entries: &[(u32, u32, u8)], vocab: u32) -> Vec<u8> {
        let mut out = Vec::new();
        out.extend_from_slice(&BIGRAM_MAGIC);
        out.push(BIGRAM_VERSION);
        out.extend_from_slice(&(entries.len() as u32).to_le_bytes());
        out.extend_from_slice(&vocab.to_le_bytes());
        for &(a, b, s) in entries {
            out.extend_from_slice(&a.to_le_bytes());
            out.extend_from_slice(&b.to_le_bytes());
            out.push(s);
        }
        out
    }

    #[test]
    fn round_trips_and_looks_up() {
        let m = BigramModel::parse(&encode(&[(1, 5, 200), (1, 9, 150), (7, 2, 90)], VOCAB), VOCAB).unwrap();
        assert_eq!(m.len(), 3);
        assert_eq!(m.score(1, 5), Some(200));
        assert_eq!(m.score(1, 9), Some(150));
        assert_eq!(m.score(7, 2), Some(90));
        assert_eq!(m.score(1, 6), None);
        assert_eq!(m.score(0, 0), None);
    }

    #[test]
    fn empty_table_is_valid() {
        let m = BigramModel::parse(&encode(&[], VOCAB), VOCAB).unwrap();
        assert!(m.is_empty());
        assert_eq!(m.score(1, 1), None);
    }

    #[test]
    fn rejects_wrong_magic_version_and_short_input() {
        assert_eq!(BigramModel::parse(b"CRKD.........", VOCAB), Err(BigramError::NotOurs));
        assert_eq!(BigramModel::parse(&[], VOCAB), Err(BigramError::NotOurs));
        let mut blob = encode(&[(1, 2, 3)], VOCAB);
        blob[4] = 9;
        assert_eq!(BigramModel::parse(&blob, VOCAB), Err(BigramError::NotOurs));
    }

    #[test]
    fn rejects_a_table_from_a_different_dictionary() {
        let blob = encode(&[(1, 5, 200)], VOCAB);
        assert_eq!(
            BigramModel::parse(&blob, VOCAB + 7),
            Err(BigramError::VocabMismatch { expected: VOCAB + 7, found: VOCAB })
        );
    }

    #[test]
    fn rejects_truncation_at_every_boundary() {
        let blob = encode(&[(1, 5, 200), (2, 6, 90)], VOCAB);
        for cut in HEADER_LEN..blob.len() {
            assert_eq!(
                BigramModel::parse(&blob[..cut], VOCAB),
                Err(BigramError::Truncated),
                "cut={cut}"
            );
        }
    }

    #[test]
    fn rejects_unsorted_and_duplicate_keys() {
        assert_eq!(
            BigramModel::parse(&encode(&[(2, 1, 10), (1, 1, 10)], VOCAB), VOCAB),
            Err(BigramError::NotSorted)
        );
        assert_eq!(
            BigramModel::parse(&encode(&[(1, 1, 10), (1, 1, 20)], VOCAB), VOCAB),
            Err(BigramError::NotSorted)
        );
    }

    #[test]
    fn rejects_absurd_count() {
        let mut blob = encode(&[], VOCAB);
        blob[5..9].copy_from_slice(&(MAX_PAIRS + 1).to_le_bytes());
        assert_eq!(
            BigramModel::parse(&blob, VOCAB),
            Err(BigramError::CountTooLarge(MAX_PAIRS + 1))
        );
    }
}
