//! GENERATED by utils/train_rescorer.py — do not edit by hand.
//!
//! Neural suggestion rescorer weights: MLP 6 -> 8 (tanh) -> 1 (sigmoid).
//! Trained 3957 synthetic fat-finger cases (seed 42) generated from the
//! measured error classes in tests/slip_corpus.rs over real QWERTY geometry,
//! with context positives drawn from the shipped CRKB bigram table.
//! Held-out top-1: neural 0.905 vs baseline 0.809
//! (566 held-out cases). No user typing was used, ever.

pub const HIDDEN: usize = 8;
pub const W1: [[f32; 6]; 8] = [[-0.3752046f32, -0.4682339f32, 0.4918458f32, 0.4694676f32, -1.079641f32, -0.801348f32], [-0.1309541f32, -0.404449f32, 0.1614833f32, -0.821759f32, 0.8040737f32, 0.3258521f32], [0.4172948f32, 0.6005642f32, 0.06278431f32, -0.3791001f32, -0.1505962f32, -0.5791876f32], [0.8373645f32, 0.1396458f32, -0.2227888f32, -0.08759208f32, 0.4464478f32, 0.2096674f32], [2.963513f32, -0.8476657f32, -0.04379346f32, 0.07157188f32, -0.1072679f32, -2.434805f32], [3.083694f32, -0.7359704f32, -0.294991f32, -0.1790377f32, -0.6211169f32, -1.867862f32], [0.7282239f32, -0.2466193f32, -0.6137136f32, 0.6038153f32, 0.2601343f32, 0.3326491f32], [0.07396752f32, 0.15201f32, -0.02404259f32, 0.215456f32, 0.4148799f32, -0.09391186f32]];
pub const B1: [f32; 8] = [0.09577555f32, -0.1833685f32, -0.08511811f32, 0.0988752f32, -1.136079f32, -0.9750958f32, 0.03581971f32, -0.02826097f32];
pub const W2: [f32; 8] = [0.8222423f32, 1.215539f32, -0.4146483f32, -0.6455503f32, -3.266035f32, -3.019042f32, -1.051618f32, -0.1282216f32];
pub const B2: f32 = 0.03294703f32;

/// Cross-language parity fixtures: feature vectors and the exact scores the
/// training-time network produced for them. rescorer.rs asserts its forward
/// pass reproduces these within 1e-4.
pub const FIXTURES: [([f32; 6], f32); 3] = [
    ([1.0f32, 0.99716f32, 0.6039216f32, 1.0f32, 1.0f32, 0.0f32], 0.001616503f32),
    ([0.1666667f32, 0.9394625f32, 0.5960784f32, 1.0f32, 0.0f32, 0.0f32], 0.988961f32),
    ([1.0f32, 0.9978742f32, 0.0f32, 1.0f32, 1.0f32, 0.0f32], 0.0007673757f32),
];
