//! GENERATED by utils/train_rescorer.py — do not edit by hand.
//!
//! Neural suggestion rescorer weights: MLP 6 -> 8 (tanh) -> 1 (sigmoid).
//! Trained 3959 synthetic fat-finger cases (seed 42) generated from the
//! measured error classes in tests/slip_corpus.rs over real QWERTY geometry,
//! with context positives drawn from the shipped CRKB bigram table.
//! Held-out top-1: neural 0.896 vs baseline 0.814
//! (566 held-out cases). No user typing was used, ever.

pub const HIDDEN: usize = 8;
pub const W1: [[f32; 6]; 8] = [[-0.3888338f32, -0.4590483f32, 0.4599472f32, 0.4534101f32, -1.09984f32, -0.763779f32], [-0.1702074f32, -0.3696363f32, 0.09248031f32, -0.8082339f32, 0.7292483f32, 0.3524405f32], [0.4062929f32, 0.5514677f32, 0.1288883f32, -0.3954338f32, -0.1031431f32, -0.6064114f32], [0.8735595f32, 0.09190392f32, -0.1755235f32, -0.09778049f32, 0.475259f32, 0.1939652f32], [2.857087f32, -0.9287995f32, -0.02698948f32, 0.08275483f32, -0.07513016f32, -2.414758f32], [3.064547f32, -0.8266911f32, -0.2609017f32, -0.1908005f32, -0.5553499f32, -1.967994f32], [0.7909633f32, -0.3166182f32, -0.5469597f32, 0.5824355f32, 0.2902355f32, 0.3046441f32], [0.1011869f32, 0.1405987f32, -0.0115121f32, 0.2253199f32, 0.4212252f32, -0.09471088f32]];
pub const B1: [f32; 8] = [0.06415546f32, -0.2208919f32, -0.06141712f32, 0.1131356f32, -1.00605f32, -0.8521035f32, 0.04318392f32, -0.01983651f32];
pub const W2: [f32; 8] = [0.7433507f32, 1.100791f32, -0.4020195f32, -0.6727674f32, -3.255919f32, -3.10485f32, -1.031457f32, -0.1633786f32];
pub const B2: f32 = 0.04963605f32;

/// Cross-language parity fixtures: feature vectors and the exact scores the
/// training-time network produced for them. rescorer.rs asserts its forward
/// pass reproduces these within 1e-4.
pub const FIXTURES: [([f32; 6], f32); 3] = [
    ([1.0f32, 0.99716f32, 0.6627451f32, 1.0f32, 1.0f32, 0.0f32], 0.00128009f32),
    ([1.0f32, 0.9751125f32, 0.572549f32, 1.0f32, 0.25f32, 0.0f32], 0.000617228f32),
    ([0.1666667f32, 0.9394625f32, 0.545098f32, 1.0f32, 0.0f32, 0.0f32], 0.988999f32),
];
