//! Neural suggestion rescorer: a 6-feature MLP (6 -> 8 tanh -> 1 sigmoid)
//! that orders the movable tail of the candidate list.
//!
//! Weights live in `rescorer_weights.rs`, generated by
//! `utils/train_rescorer.py` from a SYNTHETIC fat-finger corpus (the error
//! classes measured in tests/slip_corpus.rs applied to the real dictionary
//! over real key geometry) — no user typing is ever collected or trained on.
//! Cross-language parity is enforced: the generator embeds fixture vectors
//! with the exact scores its network produced, and a test here asserts this
//! forward pass reproduces them.
//!
//! The feature spec is shared verbatim with the trainer; change BOTH or
//! neither:
//!   f0 edit units (capped 6) / 6      f3 first letters match
//!   f1 ln(1+freq) / ln 256            f4 |len delta| (capped 4) / 4
//!   f2 bigram score / 255             f5 proper prefix completion

use crate::rescorer_weights::{B1, B2, HIDDEN, W1, W2};

/// Weighted Damerau-Levenshtein in half-units: substitution 0 same / 1 near
/// / 2 otherwise, insertion, deletion and adjacent transposition 2 — the
/// same cost table as the trie's weighted fuzzy search, over whatever `near`
/// relation the engine currently uses (live Gaussian model or fallback).
pub fn weighted_edit_units(a: &str, b: &str, near: impl Fn(char, char) -> bool) -> usize {
    let a: Vec<char> = a.chars().collect();
    let b: Vec<char> = b.chars().collect();
    if a.is_empty() || b.is_empty() {
        return 2 * a.len().max(b.len());
    }
    if a.len() > 24 || b.len() > 24 {
        return 2 * a.len().max(b.len());
    }
    let cols = b.len() + 1;
    let mut prev_prev: Vec<usize> = vec![0; cols];
    let mut prev: Vec<usize> = (0..cols).map(|j| j * 2).collect();
    let mut cur = vec![0usize; cols];
    for i in 1..=a.len() {
        cur[0] = i * 2;
        for j in 1..=b.len() {
            let sub = if a[i - 1] == b[j - 1] {
                0
            } else if near(a[i - 1], b[j - 1]) {
                1
            } else {
                2
            };
            let mut v = (prev[j] + 2).min(cur[j - 1] + 2).min(prev[j - 1] + sub);
            if i >= 2 && j >= 2 && a[i - 1] == b[j - 2] && a[i - 2] == b[j - 1] {
                v = v.min(prev_prev[j - 2] + 2);
            }
            cur[j] = v;
        }
        std::mem::swap(&mut prev_prev, &mut prev);
        std::mem::swap(&mut prev, &mut cur);
    }
    prev[b.len()]
}

/// Builds the shared feature vector. `typed` and `cand` are lowercase.
pub fn features(
    typed: &str,
    cand: &str,
    freq: u32,
    bigram: u8,
    near: impl Fn(char, char) -> bool,
) -> [f32; 6] {
    let units = weighted_edit_units(typed, cand, near).min(6) as f32;
    let len_t = typed.chars().count() as i64;
    let len_c = cand.chars().count() as i64;
    [
        units / 6.0,
        ((1.0 + freq as f32).ln()) / 256f32.ln(),
        bigram as f32 / 255.0,
        f32::from(typed.chars().next().is_some() && typed.chars().next() == cand.chars().next()),
        ((len_c - len_t).unsigned_abs().min(4)) as f32 / 4.0,
        f32::from(cand.starts_with(typed) && cand != typed),
    ]
}

/// Forward pass. Higher means "more likely the intended word".
pub fn score(f: &[f32; 6]) -> f32 {
    let mut z2 = B2;
    for h in 0..HIDDEN {
        let mut z = B1[h];
        for (i, fi) in f.iter().enumerate() {
            z += W1[h][i] * fi;
        }
        z2 += W2[h] * z.tanh();
    }
    1.0 / (1.0 + (-z2).exp())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::rescorer_weights::FIXTURES;

    #[test]
    fn forward_pass_matches_training_fixtures() {
        for (i, (f, expected)) in FIXTURES.iter().enumerate() {
            let got = score(f);
            assert!(
                (got - expected).abs() < 1e-4,
                "fixture {i}: rust {got} vs python {expected}"
            );
        }
    }

    #[test]
    fn context_evidence_raises_the_score() {
        // Same candidate shape, with and without bigram support. The trained
        // network must treat context as positive evidence — this is the
        // property the "hardly any" integration test depends on.
        let without = score(&[0.333, 0.99, 0.0, 1.0, 0.25, 1.0]);
        let with = score(&[0.333, 0.99, 0.863, 1.0, 0.25, 1.0]);
        assert!(with > without, "bigram evidence must help: {with} vs {without}");
    }

    #[test]
    fn closer_words_score_higher() {
        let near_word = score(&[1.0 / 6.0, 0.9, 0.0, 1.0, 0.0, 0.0]);
        let far_word = score(&[1.0, 0.9, 0.0, 1.0, 0.0, 0.0]);
        assert!(near_word > far_word, "{near_word} vs {far_word}");
    }

    #[test]
    fn edit_units_match_the_shared_cost_table() {
        let no_near = |_: char, _: char| false;
        let all_near = |_: char, _: char| true;
        assert_eq!(weighted_edit_units("an", "an", no_near), 0);
        assert_eq!(weighted_edit_units("an", "any", no_near), 2); // insertion
        assert_eq!(weighted_edit_units("xan", "can", all_near), 1); // near sub
        assert_eq!(weighted_edit_units("xan", "can", no_near), 2); // far sub
        assert_eq!(weighted_edit_units("", "abc", no_near), 6);
        // Adjacent transposition is a single edit (2 units), matching the
        // trie's Damerau-weighted search.
        assert_eq!(weighted_edit_units("thnaks", "thanks", no_near), 2);
        assert_eq!(weighted_edit_units("tesitng", "testing", no_near), 2);
    }
}
