//! GENERATED by utils/train_rescorer.py — do not edit by hand.
//!
//! Neural suggestion rescorer weights: MLP 6 -> 8 (tanh) -> 1 (sigmoid).
//! Trained 3958 synthetic fat-finger cases (seed 42) generated from the
//! measured error classes in tests/slip_corpus.rs over real QWERTY geometry,
//! with context positives drawn from the shipped CRKB bigram table.
//! Held-out top-1: neural 0.919 vs baseline 0.843
//! (566 held-out cases). No user typing was used, ever.

pub const HIDDEN: usize = 8;
pub const W1: [[f32; 6]; 8] = [[-0.4039616f32, -0.4627175f32, 0.469548f32, 0.4362703f32, -1.101879f32, -0.7475809f32], [-0.1659993f32, -0.3648646f32, 0.09256276f32, -0.8036442f32, 0.7246214f32, 0.3682471f32], [0.4008998f32, 0.5770639f32, 0.1178912f32, -0.3497344f32, -0.1089499f32, -0.6104993f32], [0.8722696f32, 0.08970358f32, -0.1907587f32, -0.07899008f32, 0.4558818f32, 0.1356004f32], [2.785803f32, -0.9089267f32, -0.04044624f32, 0.06820352f32, -0.05566689f32, -2.323414f32], [3.140273f32, -0.8377977f32, -0.2568013f32, -0.1894281f32, -0.5150828f32, -1.979946f32], [0.7636354f32, -0.307301f32, -0.5605045f32, 0.6064175f32, 0.3138995f32, 0.282672f32], [0.08382287f32, 0.139145f32, -0.009942298f32, 0.2167694f32, 0.4294049f32, -0.09500567f32]];
pub const B1: [f32; 8] = [0.06334214f32, -0.2134305f32, -0.03119332f32, 0.1046732f32, -0.9777247f32, -0.8703089f32, 0.05600783f32, -0.01937415f32];
pub const W2: [f32; 8] = [0.7390682f32, 1.101663f32, -0.4323926f32, -0.6505985f32, -3.160203f32, -3.174258f32, -1.035608f32, -0.1538768f32];
pub const B2: f32 = 0.04457205f32;

/// Cross-language parity fixtures: feature vectors and the exact scores the
/// training-time network produced for them. rescorer.rs asserts its forward
/// pass reproduces these within 1e-4.
pub const FIXTURES: [([f32; 6], f32); 3] = [
    ([1.0f32, 0.99716f32, 0.6039216f32, 1.0f32, 1.0f32, 0.0f32], 0.001016223f32),
    ([0.1666667f32, 0.9394625f32, 0.5960784f32, 1.0f32, 0.0f32, 0.0f32], 0.9884507f32),
    ([1.0f32, 0.9978742f32, 0.0f32, 1.0f32, 1.0f32, 0.0f32], 0.000590531f32),
];
